version: "3.8"

services:
  mplan_backend:
    container_name: mplan_backend
    image: mplan_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      # bind logs
      - backend_logs:/app/logs
      # bind volume
      - ./backend:/app
      # anonymous volume
      - /app/node_modules
    env_file:
      - ./env/backend.env      
    ports:
      - 8000:8000
      - 9229:9229
    depends_on:
      - mplan_db
    networks:
      - mplan

  mplan_db:
    container_name: mplan_db
    image: "mongo:5.0.0"
    volumes:
      - data:/data/db
      - ./mongo/mongo-init-plans.js:/docker-entrypoint-initdb.d/mongo-init-plans.js:ro
    env_file:
      - ./env/mongo.env
    networks:
      - mplan

  mplan_frontend:
    container_name: mplan_frontend
    image: mplan_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      # bind logs
      - frontend_logs:/app/logs
      # bind volume
      - ./frontend:/app
      # anonymous mount
      - /app/node_modules
    env_file:
      - ./env/frontend.env
    ports:
      - 3000:3000
    networks:
      - mplan
  

volumes:
  backend_logs:
  frontend_logs:
  data:

networks:
  mplan: